# Perceptron learning - Example

In [1]:
import numpy as np
import pandas as pd
import random

#xor matrix
input_matrix =  np.array([[0,0,0],[0,1,1],[1,0,1]])

#xor output
output = np.array([0,0,1]).T
weights_init = (2*np.random.random((2,1)) - 1)[:,0]
weights_init = np.append(weights_init,1)

print ("Matrix \n", input_matrix)
print("Output \n", output)
print("Weights \n", weights_init)


Matrix 
 [[0 0 0]
 [0 1 1]
 [1 0 1]]
Output 
 [0 0 1]
Weights 
 [-0.7953433  -0.01511515  1.        ]


# Step function
Helps us check if the weight vector and the input vector are pointing in the same direction. <br\>
                                   
`w.x > 0 - same direction` <br\>
`w.x < 0 - opposite direction`<br\>


In [2]:
#activation function
def step_function(output_vector):
    result = np.zeros(len(output_vector))
    max_len = len(output_vector)
    i=0
    for o in output_vector:
        if o <0:result[i] = 0
        elif o>0:result[i]=1
        i=i+1
    return np.array(result)


In [3]:
def perceptron_learning():
    pred_y = 0
    weights = weights_init
    class_error = 100
    while class_error>0.5: 
        w_dot_i = np.dot(weights,input_matrix.T)
        computed_output = step_function(w_dot_i)
        output_delta =  output - computed_output
        class_error = float(classification_error(computed_output,output))
        w_delta = np.dot(output_delta,input_matrix)
        weights = weights + w_delta
    return weights

def classification_error(computed_output,output):
    total_correct = np.sum(computed_output == output) 
    total_incorrect = np.sum(computed_output!=output)
    pc_correct = total_incorrect/len(output)
    return pc_correct

In [4]:
w = perceptron_learning()
print("computed weights",w)

computed weights [-0.7953433  -1.01511515  0.        ]


In [5]:
print("Result of output ", step_function([np.dot(w,[1,1,0])])[0])

Result of output  0.0
